# Generated by Django 5.1 on 2024-09-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cohortschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohortschedule',
            name='description',
        ),
    ]
