# Generated by Django 5.1 on 2024-09-11 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('payment_gateway', models.CharField(choices=[('stripe', 'stripe'), ('paystack', 'paystack')], max_length=25)),
                ('gateway_unique_id', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subscriptionplan')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subscriber')),
            ],
        ),
    ]
