# Generated by Django 5.1 on 2024-09-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_phonenumber_subscriber_phone_number_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway_unique_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
