# Generated by Django 5.1 on 2024-09-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_payment_gateway_unique_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
