# Generated by Django 5.1 on 2024-09-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_gateway_unique_id_payment_paystack_unique_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='status',
            new_name='is_confirmed',
        ),
    ]
